baseURL = "https://matplotlib.github.io/matplotblog/"
languageCode = "en-us"
title = "Matplotblog"
theme = "aether"
canonifyurls = true
paginate = 3

[params]
head_img = "/mpl_logo.png"
description = "The blog of Matplotlib"
bgimg = "bg_tiles.png"
link1 = "https://matplotlib.org"
link1_description = "About"

[taxonomies]
  category = "categories"
